# Generated by Django 2.1.4 on 2019-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_measure_objective_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
