# Generated by Django 2.1.4 on 2019-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190219_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('evaluation_status', models.BooleanField()),
                ('evaluation_score', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='RubricFile',
            new_name='StudentList',
        ),
        migrations.RenameField(
            model_name='studentlist',
            old_name='data',
            new_name='StudentList',
        ),
    ]
